import 'package:flutter/material.dart';

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  String _currentLanguage = 'English';
  
  String get currentLanguage => _currentLanguage;
  
  final Map<String, String> _supportedLanguages = {
    'English': 'en',
    'हिंदी': 'hi',
    'বাংলা': 'bn',
    'অসমীয়া': 'as',
    'नेपाली': 'ne',
    'मणिपुरी': 'mni',
  };

  Map<String, String> get supportedLanguages => _supportedLanguages;

  void setLanguage(String language) {
    if (_supportedLanguages.containsKey(language)) {
      _currentLanguage = language;
      notifyListeners();
    }
  }

  String translate(String key) {
    final languageCode = _supportedLanguages[_currentLanguage] ?? 'en';
    return _translations[languageCode]?[key] ?? key;
  }

  // Translation data for key features
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'FlowSafe',
      'water_quality_monitoring': 'Water Quality Monitoring',
      'disease_surveillance': 'Disease Surveillance',
      'hygiene_education': 'Hygiene & Disease Prevention',
      'current_location': 'Current Location',
      'water_source': 'Water Source',
      'ph_level': 'pH Level',
      'turbidity': 'Turbidity',
      'bacterial_count': 'Bacterial Count',
      'patient_name': 'Patient Name',
      'age': 'Age',
      'symptoms': 'Symptoms',
      'submit_report': 'Submit Report',
      'good_quality': 'Good Quality',
      'poor_quality': 'Poor Quality - Requires Treatment',
      'diarrhea': 'Diarrhea',
      'cholera': 'Cholera',
      'typhoid': 'Typhoid',
      'hepatitis_a': 'Hepatitis A',
      'fever': 'Fever',
      'vomiting': 'Vomiting',
      'dehydration': 'Dehydration',
      'hand_washing': 'Proper Handwashing',
      'safe_water': 'Safe Water Practices',
      'food_safety': 'Food Safety',
      'prevention_tips': 'Disease Prevention Tips',
    },
    'hi': {
      'app_name': 'फ्लोसेफ',
      'water_quality_monitoring': 'जल गुणवत्ता निगरानी',
      'disease_surveillance': 'रोग निगरानी',
      'hygiene_education': 'स्वच्छता और रोग रोकथाम',
      'current_location': 'वर्तमान स्थान',
      'water_source': 'जल स्रोत',
      'ph_level': 'पीएच स्तर',
      'turbidity': 'टर्बिडिटी',
      'bacterial_count': 'बैक्टीरिया की संख्या',
      'patient_name': 'रोगी का नाम',
      'age': 'उम्र',
      'symptoms': 'लक्षण',
      'submit_report': 'रिपोर्ट जमा करें',
      'good_quality': 'अच्छी गुणवत्ता',
      'poor_quality': 'खराब गुणवत्ता - उपचार आवश्यक',
      'diarrhea': 'दस्त',
      'cholera': 'हैजा',
      'typhoid': 'टाइफाइड',
      'hepatitis_a': 'हेपेटाइटिस ए',
      'fever': 'बुखार',
      'vomiting': 'उल्टी',
      'dehydration': 'निर्जलीकरण',
      'hand_washing': 'सही तरीके से हाथ धोना',
      'safe_water': 'सुरक्षित पानी के तरीके',
      'food_safety': 'खाद्य सुरक्षा',
      'prevention_tips': 'रोग रोकथाम के उपाय',
    },
    'bn': {
      'app_name': 'ফ্লোসেফ',
      'water_quality_monitoring': 'পানির গুণমান নিরীক্ষণ',
      'disease_surveillance': 'রোগ নিরীক্ষণ',
      'hygiene_education': 'স্বাস্থ্যবিধি ও রোগ প্রতিরোধ',
      'current_location': 'বর্তমান অবস্থান',
      'water_source': 'পানির উৎস',
      'ph_level': 'পিএইচ স্তর',
      'turbidity': 'ঘোলাত্ব',
      'bacterial_count': 'ব্যাকটেরিয়ার সংখ্যা',
      'patient_name': 'রোগীর নাম',
      'age': 'বয়স',
      'symptoms': 'উপসর্গ',
      'submit_report': 'রিপোর্ট জমা দিন',
      'good_quality': 'ভাল মানের',
      'poor_quality': 'খারাপ মানের - চিকিৎসা প্রয়োজন',
      'diarrhea': 'ডায়রিয়া',
      'cholera': 'কলেরা',
      'typhoid': 'টাইফয়েড',
      'hepatitis_a': 'হেপাটাইটিস এ',
      'fever': 'জ্বর',
      'vomiting': 'বমি',
      'dehydration': 'পানিশূন্যতা',
      'hand_washing': 'সঠিক হাত ধোয়া',
      'safe_water': 'নিরাপদ পানির অনুশীলন',
      'food_safety': 'খাদ্য নিরাপত্তা',
      'prevention_tips': 'রোগ প্রতিরোধের টিপস',
    },
    'as': {
      'app_name': 'ফ্লৌছেফ',
      'water_quality_monitoring': 'পানীৰ গুণগত মান নিৰীক্ষণ',
      'disease_surveillance': 'ৰোগ নিৰীক্ষণ',
      'hygiene_education': 'স্বাস্থ্যবিধি আৰু ৰোগ প্ৰতিৰোধ',
      'current_location': 'বৰ্তমান অৱস্থান',
      'water_source': 'পানীৰ উৎস',
      'ph_level': 'পিএইচ স্তৰ',
      'turbidity': 'ঘোলা',
      'bacterial_count': 'বেক্টেৰিয়াৰ সংখ্যা',
      'patient_name': 'ৰোগীৰ নাম',
      'age': 'বয়স',
      'symptoms': 'লক্ষণ',
      'submit_report': 'প্ৰতিবেদন দাখিল কৰক',
      'good_quality': 'ভাল মানৰ',
      'poor_quality': 'বেয়া মানৰ - চিকিৎসা প্ৰয়োজন',
      'diarrhea': 'ডায়েৰিয়া',
      'cholera': 'কলেৰা',
      'typhoid': 'টাইফয়েড',
      'hepatitis_a': 'হেপাটাইটিছ এ',
      'fever': 'জ্বৰ',
      'vomiting': 'বমি',
      'dehydration': 'পানী শূন্যতা',
      'hand_washing': 'সঠিক হাত ধোৱা',
      'safe_water': 'নিৰাপদ পানীৰ অভ্যাস',
      'food_safety': 'খাদ্য নিৰাপত্তা',
      'prevention_tips': 'ৰোগ প্ৰতিৰোধৰ টিপছ',
    },
    'ne': {
      'app_name': 'फ्लोसेफ',
      'water_quality_monitoring': 'पानीको गुणस्तर निगरानी',
      'disease_surveillance': 'रोग निगरानी',
      'hygiene_education': 'स्वच्छता र रोग रोकथाम',
      'current_location': 'हालको स्थान',
      'water_source': 'पानीको स्रोत',
      'ph_level': 'पीएच स्तर',
      'turbidity': 'टर्बिडिटी',
      'bacterial_count': 'ब्याक्टेरियाको संख्या',
      'patient_name': 'बिरामीको नाम',
      'age': 'उमेर',
      'symptoms': 'लक्षणहरू',
      'submit_report': 'रिपोर्ट पेश गर्नुहोस्',
      'good_quality': 'राम्रो गुणस्तर',
      'poor_quality': 'खराब गुणस्तर - उपचार आवश्यक',
      'diarrhea': 'पखाला',
      'cholera': 'हैजा',
      'typhoid': 'टाइफाइड',
      'hepatitis_a': 'हेपाटाइटिस ए',
      'fever': 'ज्वरो',
      'vomiting': 'बान्ता',
      'dehydration': 'निर्जलीकरण',
      'hand_washing': 'सही तरिकाले हात धुने',
      'safe_water': 'सुरक्षित पानीका अभ्यासहरू',
      'food_safety': 'खाद्य सुरक्षा',
      'prevention_tips': 'रोग रोकथामका सुझावहरू',
    },
    'mni': {
      'app_name': 'ꯐ꯭ꯂꯣꯁꯦꯐ',
      'water_quality_monitoring': 'ꯏꯁꯤꯡꯒꯤ ꯊꯣꯀꯄꯥ ꯌꯦꯡꯁꯤꯟꯅꯕꯥ',
      'disease_surveillance': 'ꯅꯥꯕꯥ ꯌꯦꯡꯁꯤꯟꯅꯕꯥ',
      'hygiene_education': 'ꯑꯁꯦꯡꯕꯥ ꯑꯃꯁꯨꯡ ꯅꯥꯕꯥ ꯊꯤꯡꯖꯤꯟꯅꯕꯥ',
      'current_location': 'ꯍꯧꯖꯤꯛꯀꯤ ꯃꯐꯝ',
      'water_source': 'ꯏꯁꯤꯡꯒꯤ ꯃꯐꯝ',
      'ph_level': 'ꯄꯤ.ꯑꯦꯆ. ꯂꯦꯚꯦꯜ',
      'turbidity': 'ꯇꯔꯕꯤꯗꯤꯇꯤ',
      'bacterial_count': 'ꯕꯦꯛꯇꯦꯔꯤꯌꯥꯁꯤꯡꯒꯤ ꯃꯁꯤꯡ',
      'patient_name': 'ꯑꯅꯥꯕꯥ ꯃꯤꯑꯣꯏꯒꯤ ꯃꯤꯡ',
      'age': 'ꯆꯍꯤ',
      'symptoms': 'ꯃꯔꯝ ꯑꯣꯏꯕꯁꯤꯡ',
      'submit_report': 'ꯔꯤꯄꯣꯔꯠ ꯄꯤꯌꯨ',
      'good_quality': 'ꯐꯕꯥ ꯊꯣꯀꯄꯥ',
      'poor_quality': 'ꯑꯁꯥꯑꯣꯕꯥ ꯊꯣꯀꯄꯥ - ꯄꯥꯟꯅꯔꯤ',
      'diarrhea': 'ꯀꯝꯖꯣ',
      'cholera': 'ꯀꯦꯂꯦꯔꯥ',
      'typhoid': 'ꯇꯥꯏꯐꯥꯏꯗ',
      'hepatitis_a': 'ꯍꯦꯄꯥꯇꯥꯏꯇꯤꯁ ꯑꯦ',
      'fever': 'ꯂꯥꯏ',
      'vomiting': 'ꯁꯦꯟꯊꯣꯛ',
      'dehydration': 'ꯏꯁꯤꯡ ꯊꯣꯡꯗꯣꯀꯄꯥ',
      'hand_washing': 'ꯈꯨꯠ ꯊꯣꯡꯗꯣꯀꯄꯥ',
      'safe_water': 'ꯑꯁꯣꯛ-ꯑꯁꯅꯕꯥ ꯏꯁꯤꯡ',
      'food_safety': 'ꯆꯥꯅꯕꯥ ꯔꯛꯁꯅꯕꯥ',
      'prevention_tips': 'ꯅꯥꯕꯥ ꯊꯤꯡꯖꯤꯟꯅꯕꯒꯤ ꯄꯥꯝꯕꯩꯁꯤꯡ',
    },
  };
}
